[workspace]

members = [
  "zenoh",
  "zenoh-ffi",
  "zenoh-protocol",
  "zenoh-router",
  "zenoh-util",
  "plugins/example-plugin"
]

exclude = [
  "zenoh-perf"
]

[profile.release]
debug=false
lto = true
codegen-units = 1
opt-level = 3
