[package]
name = "zenoh-perf"
version = "0.5.0"
authors = ["kydos <angelo@icorsaro.net>",
           "Julien Enoch <julien@enoch.fr>",
           "Olivier Hécart <olivier.hecart@adlinktech.com",
		   "Luca Cominardi <luca.cominardi@adlinktech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.31"
env_logger = "0.7.1"
log = "0.4.8"
rand = "0.7.3"
slab = "0.4.2"
time = "0.2.16"
uuid = { version = "0.8.1", features = ["v4"] }
zenoh-protocol =  { version = "0.5.0", path = "../zenoh-protocol" }
zenoh-router =  { version = "0.5.0", path = "../zenoh-router" }
zenoh-util =  { version = "0.1.0", path = "../zenoh-util" }

[dependencies.async-std]
version = "~1.6.0"
features = ["unstable"]

[profile.release]
debug=false
lto = true
codegen-units = 1
opt-level = 3

[[bin]]
name = "session_thr_sink_tcp"
test = false
bench = false

[[bin]]
name = "session_thr_sub_peer"
test = false
bench = false

[[bin]]
name = "session_thr_pub_peer"
test = false
bench = false

[[bin]]
name = "session_thr_pubsub_peer"
test = false
bench = false

[[bin]]
name = "session_thr_sub_client"
test = false
bench = false

[[bin]]
name = "session_thr_pub_client"
test = false
bench = false

[[bin]]
name = "session_thr_pubsub_client"
test = false
bench = false

[[bin]]
name = "session_thr_broker"
test = false
bench = false


[[bin]]
name = "router_thr_sub_peer"
test = false
bench = false

[[bin]]
name = "router_thr_pub_peer"
test = false
bench = false

[[bin]]
name = "router_thr_sub_client"
test = false
bench = false

[[bin]]
name = "router_thr_pub_client"
test = false
bench = false

[[bin]]
name = "router_thr_sub_light_client"
test = false
bench = false

[[bin]]
name = "router_thr_pub_light_client"
test = false
bench = false


[[bin]]
name = "util_fifo_queue"
test = false
bench = false

[[bin]]
name = "util_priority_queue"
test = false
bench = false

[[bin]]
name = "util_credit_queue"
test = false
bench = false

[[bin]]
name = "util_credit_queue_batching"
test = false
bench = false
