[package]
name = "zenoh-protocol"
version = "0.5.0"
authors = ["kydos <angelo@icorsaro.net>",
           "Julien Enoch <julien@enoch.fr>",
           "Olivier Hécart <olivier.hecart@adlinktech.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "0.8.1"
byteorder = "1.3.2"
time = "0.2.2"
net2 = "0.2.33"
log = "0.4.8"
env_logger = "0.7.1"
# mio = {git = "https://github.com/tokio-rs/mio"}
rand = "0.7.3"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "codec_bench"
harness = false