[package]
name = "zenoh-util"
version = "0.1.0"
authors = ["kydos <angelo@icorsaro.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.5.0", features = ["unstable"] }
futures = { version = "0.3.4", features = ["unstable"] }

[[example]]
name = "async_queue"
path = "examples/async_queue.rs"
