name: Rust

on:
  push:
    branches: [ rust-master ]
  pull_request:
    branches: [ rust-master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-targets
    - name: Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
